#
#         ________          ________          ________          ________
#        |        |\       |        |\       |        |\       |        |\
#        |        |:\      |        |:\      |        |:\      |        |:\
#        |        |::\     |   	    |::\     |        |::\     |        |::\
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |:::|    |	    |:::|    |        |:::|    |        |:::|
#        |        |:::|    |	    |:::|    |        |:::|    |        |:::|
#        |        |:::|    |	    |:::|    |        |:::|    |        |:::|
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |:::|    |	    |:::|    |        |:::|    |        |:::|
#        |        |:::|    |        |:::|    |        |:::|    |        |:::|
#        |        |___|____|        |___|____|        |___|____|        |:::|
#        |                                                              |:::|
#        |                                                              |:::|
#        |______________________________________________________________|:::|
#         \::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\::|
#          \_______________________________________________________________\|
#








#####################################################################################
##############################|                        |#############################
##############################| SHESH ALACRITTY CONFIG |#############################
##############################|                        |#############################
#####################################################################################
#                                                                                   #
#                             created 2024-05-05                                    #
#                             last modified 2024-05-05                              #
#                                                                                   #
#                    Read `man alacritty` for a complete reference.                 #
#                                                                                   #
#####################################################################################

[keyboard]
bindings = [
    # spawn new instance in same cwd
   { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]
